### ISSUE TITLE
Add WordPress benchmark

### ISSUE THREAD

**Issue by pronskiy** [kocsismate/php-version-benchmarks#7]
It would be great to test on a default WordPress set-up in addition to the Symfony and Laravel demo apps.

**Comment by kocsismate** [comment]
Hi Roman,

Adding Wordpress to the benchmark suite was my plan initially. However, it was a PITA to set it up automatically, so I postponed it. My main problem with Wordpress is that it relies on a database connection, so I'm a bit worried that the benchmark result would primarily depend on the DB performance  rather than the PHP execution time itself. Nevertheless, I can try setting Wordpress up in the close future.

**Comment by kocsismate** [comment]
I've just added support for running benchmark for Wordpress in https://github.com/kocsismate/php-version-benchmarks/commit/b174d6b304d716555130f28ba7aee853a00bc6c5. I've not shared results yet, but PHP 8.4 is around 3% faster currently than PHP 8.3. Thanks for your patience ^^

**Comment by kocsismate** [comment]
New results: https://github.com/kocsismate/php-version-benchmarks/blob/main/docs/results/2024_06_23_09_39_1_aws_x86_64_c7i_metal_24xl/result.md
